# Generated by Django 5.1.3 on 2024-12-05 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=50, null=True)),
                ('amount', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'restock',
            },
        ),
        migrations.CreateModel(
            name='Returned',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=50, null=True)),
                ('returned_date', models.DateField()),
                ('returned_product', models.CharField(max_length=50)),
                ('returned_by', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'returned',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=50, null=True)),
                ('product_id', models.CharField(max_length=50, unique=True)),
                ('price', models.IntegerField(default=0, null=True)),
                ('quantity', models.IntegerField(null=True)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('initial_quantity', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ice',
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_bought', models.IntegerField(default=0)),
                ('amount', models.IntegerField()),
                ('sold_by', models.CharField(max_length=50, null=True)),
                ('bought_by', models.CharField(max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stocks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capital.stock')),
            ],
            options={
                'db_table': 'lemon',
            },
        ),
    ]
