# Generated by Django 5.1.3 on 2024-11-26 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capital', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('product', models.CharField(max_length=50, null=True)),
                ('status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stocks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capital.stock')),
            ],
            options={
                'db_table': 'lemon',
            },
        ),
    ]
