# Generated by Django 5.1.3 on 2024-11-26 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capital', '0002_purchase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='product',
        ),
        migrations.AlterField(
            model_name='stock',
            name='price',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
